version: '3.1'

services:

  mongo:
    image: mongo:5.0
    restart: always
    
   
    ports:
      - 27017:27017
    volumes:
      - $PWD:/app

# terminal container >> docker exec -it  sd-019-c-mongodb-commerce_mongo_1  bash
